# Dependabot configuration for automated dependency updates
# Replaces complex vulnerability scanning with simpler automation
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Rust dependencies (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    # Security-focused updates
    assignees:
      - "tbowman01"
    reviewers:
      - "tbowman01"
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    # Group related updates
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific dependencies if needed
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Auto-merge configuration
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "semver:patch"
    # Labels
    labels:
      - "dependencies"
      - "security"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    assignees:
      - "tbowman01"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automated"

  # WASM package.json (if present)
  - package-ecosystem: "npm"
    directory: "/wasm"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    assignees:
      - "tbowman01"
    groups:
      wasm-dev-dependencies:
        applies-to: version-updates
        patterns:
          - "@types/*"
          - "typescript"
          - "webpack*"
          - "wasm-pack"
        update-types:
          - "minor"
          - "patch"
      wasm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - "wasm"
      - "javascript"
      - "dependencies"
      - "automated"