# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`  
wildcards = "allow"
# Lint level for when a crate is marked as Deprecated on crates.io
deprecated = "warn"

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices
notice = "warn"
# A list of advisory IDs to ignore.
ignore = []

[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "Unicode-DFS-2016",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
]
# List of explicitly disallowed licenses
deny = []
# Lint level for when a crate has a license that is not in the allow or deny lists
copyleft = "warn"
# Blanket approval or denial for OSI-approved or FSF-approved licenses
allow-osi-fsf-free = "either"
# Lint level used when no other predicates are matched
default = "deny"
# The confidence threshold for detecting a license from a license text.
confidence-threshold = 0.8

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []