/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PhotonDrift",
  "tagline": "AI-Powered Architecture Decision Record Management with ML-Enhanced Drift Detection",
  "favicon": "img/favicon.ico",
  "url": "https://docs.photondrift.dev",
  "baseUrl": "/",
  "organizationName": "tbowman01",
  "projectName": "PhotonDrift",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/workspaces/PhotonDrift/docs-site/sidebars.js",
          "editUrl": "https://github.com/tbowman01/PhotonDrift/tree/main/docs/",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "remarkPlugins": [],
          "rehypePlugins": []
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/tbowman01/PhotonDrift/tree/main/docs-site/blog/",
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts"
        },
        "theme": {
          "customCss": "/workspaces/PhotonDrift/docs-site/src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-PLACEHOLDER",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": false,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/photondrift_logo.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "/img/photondrift_logo.png"
          },
          {
            "tagName": "link",
            "rel": "mask-icon",
            "href": "/img/photondrift_logo.png",
            "color": "rgb(37, 194, 160)"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "/img/photondrift_logo.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    "plugin-image-zoom"
  ],
  "themeConfig": {
    "image": "img/photondrift-social-card.jpg",
    "navbar": {
      "title": "PhotonDrift",
      "logo": {
        "alt": "PhotonDrift Logo",
        "src": "img/photondrift_logo.png",
        "srcDark": "img/photondrift_logo_dark.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "gettingStartedSidebar",
          "position": "left",
          "label": "🚀 Get Started"
        },
        {
          "type": "docSidebar",
          "sidebarId": "apiSidebar",
          "position": "left",
          "label": "📖 CLI Reference"
        },
        {
          "type": "docSidebar",
          "sidebarId": "guidesSidebar",
          "position": "left",
          "label": "📚 Guides"
        },
        {
          "href": "https://github.com/tbowman01/PhotonDrift",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Quick Start",
              "to": "/docs/getting-started/quick-start"
            },
            {
              "label": "CLI Reference",
              "to": "/docs/getting-started/cli"
            },
            {
              "label": "Configuration",
              "to": "/docs/getting-started/config"
            }
          ]
        },
        {
          "title": "Development",
          "items": [
            {
              "label": "Contributing",
              "to": "/docs/development/development"
            },
            {
              "label": "Architecture",
              "to": "/docs/architecture/architecture-enhancements"
            },
            {
              "label": "ADRs",
              "to": "/docs/adr/0001-use-rust-for-cli"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/tbowman01/PhotonDrift"
            },
            {
              "label": "Issues",
              "href": "https://github.com/tbowman01/PhotonDrift/issues"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/tbowman01/PhotonDrift/discussions"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "Releases",
              "href": "https://github.com/tbowman01/PhotonDrift/releases"
            },
            {
              "label": "Changelog",
              "href": "https://github.com/tbowman01/PhotonDrift/blob/main/CHANGELOG.md"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 PhotonDrift. Built with Docusaurus. <br/>🤖 Powered by AI-Enhanced Architecture Decision Record Management"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "rust",
        "toml",
        "yaml",
        "docker",
        "bash",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "ALGOLIA_APP_ID_PLACEHOLDER",
      "apiKey": "ALGOLIA_SEARCH_API_KEY_PLACEHOLDER",
      "indexName": "photondrift-docs",
      "contextualSearch": true,
      "searchParameters": {
        "facetFilters": [
          "language:en"
        ]
      },
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "architecture, decisions, records, ADR, documentation, CLI, rust, AI, ML, drift-detection"
      },
      {
        "name": "description",
        "content": "PhotonDrift - AI-Powered Architecture Decision Record Management with ML-Enhanced Drift Detection. Revolutionary CLI tool for intelligent development governance."
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:description",
        "content": "Revolutionary Architecture Decision Record (ADR) management with AI-powered drift detection and intelligent insights."
      }
    ],
    "announcementBar": {
      "id": "support_us",
      "content": "⭐️ If you like PhotonDrift, give it a star on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/tbowman01/PhotonDrift\">GitHub</a>! ⭐️",
      "backgroundColor": "#fafbfc",
      "textColor": "#091E42",
      "isCloseable": true
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
